version: "3.9"

services:
  instacart:
    image: postgres:16
    container_name: instacart
    restart: unless-stopped
    environment:
      POSTGRES_USER: instacart
      POSTGRES_PASSWORD: instacart123
      POSTGRES_DB: instacart
    ports:
      - "5433:5432"
    volumes:
      - instacart_data:/var/lib/postgresql/data

volumes:
  instacart_data: